# Default values for hierarchical-namespace-controller.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: gcr.io
  name: k8s-staging-multitenancy/hnc-manager
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

customLabels: {}
  #control-plane: controller-manager

securityContext:
  fsGroup: 2000
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 100m
    memory: 300Mi
  requests:
    cpu: 100m
    memory: 150Mi

extraVolumes: []
extraVolumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}

args:
  - --webhook-server-port=9443
  - --metrics-addr=:8080
  - --max-reconciles=10
  - --apiserver-qps-throttle=50
  - --enable-internal-cert-management
  - --cert-restart-on-secret-refresh
  - --excluded-namespace=kube-system
  - --excluded-namespace=kube-public
  - --excluded-namespace=hnc-system
  - --excluded-namespace=kube-node-lease

terminationGracePeriodSeconds: 10
