---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hnc-controller-manager
  labels:
{{- include "hierarchical-namespace-controller.labels" . | nindent 4 }}
{{- with .Values.customLabels }}
{{- toYaml . | nindent 4 }}
{{- end }}
  annotations:
   {{- toYaml .Values.annotations | nindent 8 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
{{- include "hierarchical-namespace-controller.selectorLabels" . | nindent 6 }}
{{- with .Values.customLabels }}
{{- toYaml . | nindent 6 }}
{{- end }}
  template:
    metadata:
      labels:
{{- include "hierarchical-namespace-controller.selectorLabels" . | nindent 8 }}
{{- with .Values.customLabels }}
{{- toYaml . | nindent 6 }}
{{- end }}
    spec:
      containers:
      - command:
        - /manager
{{- if .Values.args }}
        args:
{{ toYaml .Values.args | indent 10 }}
{{- end }}
        command:
        - /manager
        image: {{ include "hierarchical-namespace-controller.image" . }}
        name: manager
        ports:
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
          {{- with .Values.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
          {{- end }}
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
{{- if ne (len .Values.extraVolumeMounts) 0 }}
{{ toYaml .Values.extraVolumeMounts | indent 8 }}
{{- end }}
      - args:
        - --upstream=http://127.0.0.1:8080/
        - --secure-listen-address=0.0.0.0:8443
        - --logtostderr=true
        - --v=10
        image: gcr.io/kubebuilder/kube-rbac-proxy:v0.4.0
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: https
      {{- if .Values.securityContext }}
      securityContext:
{{ toYaml .Values.securityContext | indent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: hnc-webhook-server-cert
{{- if ne (len .Values.extraVolumes) 0 }}
{{ toYaml .Values.extraVolumes | indent 6 }}
{{- end }}
