---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "8443"
    prometheus.io/scheme: https
    prometheus.io/scrape: "true"
  labels:
{{- include "hierarchical-namespace-controller.labels" . | nindent 4 }}
  name: hnc-controller-manager-metrics-service
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
{{- include "hierarchical-namespace-controller.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: hnc-webhook-service
  namespace: hnc-system
spec:
  ports:
  - port: 443
    targetPort: 9443
  selector:
{{- include "hierarchical-namespace-controller.selectorLabels" . | nindent 4 }}
