name: Helm Chart

on:
  push:
    branches:
      - main

jobs:
  push-chart:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Push Helm Chart to ChartMuseum
      uses: bsord/helm-push@v4
      with:
        username: ${{ secrets.CHARTMUSEUM_USER }}
        password: ${{ secrets.CHARTMUSEUM_PASSWORD }}
        registry-url: 'https://charts.softonic.io'
        force: true
        chart-folder: chart
